services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: always

volumes: {}
